apiVersion: v1
kind: Service
metadata:
  name: grafana-metrics
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'http'
spec:
  ports:
    - name: grafana-metrics
      port: 9779
      targetPort: 3000
  selector:
    app: grafana

# Direct access from ingress without oauth-proxy
