kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: grafana
  template:
    metadata:
      labels:
        deployment: grafana
    spec:
      serviceAccountName: grafana
      containers:
        - name: oauth-proxy
          image: oauth-proxy-image
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAME_SPACE_ROUTE
              value: 'oauth-openshift.apps.guid.it-speeltuin.eu'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 32Mi
          ports:
            - containerPort: 8443
              name: web
          args:
            - -provider=openshift
            - -proxy-prefix=/oauth2
            - -login-url=https://$(NAME_SPACE_ROUTE)/oauth/authorize
            - -redeem-url=https://$(NAME_SPACE_ROUTE)/oauth/token
            - -https-address=:8443
            - -http-address=
            - '-email-domain=*'
            - -upstream=http://localhost:3000
            - -tls-cert=/etc/tls/private/tls.crt
            - -tls-key=/etc/tls/private/tls.key
            - -openshift-service-account=grafana
            - -cookie-secret-file=/etc/proxy/secrets/session_secret
            - -cookie-refresh=0
            - -cookie-expire=24h0m0s
            - -cookie-name=_oauth2_graf
            - -ssl-insecure-skip-verify=true
            - -request-logging=true
            - '-openshift-sar={"namespace": "$(NAMESPACE)", "verb": "list", "resource": "services"}'
          volumeMounts:
            - mountPath: /etc/tls/private
              name: grafana-tls
            - mountPath: /etc/proxy/secrets
              name: secrets

        - name: grafana
          image: grafana-image
          args:
            - -config=/etc/grafana/grafana.ini
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAME_SPACE_ROUTE
              value: 'oauth-openshift.apps.guid.it-speeltuin.eu'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: grafana-http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-tls
              mountPath: /etc/tls/private
            - name: secrets
              mountPath: /etc/proxy/secrets
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-datasources
          secret:
            secretName: grafana-datasources
        - name: secrets
          secret:
            secretName: grafana-proxy
        - name: grafana-tls
          secret:
            secretName: grafana-tls
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 600

